task "clean", "Clean up build directories", ->
  console.log "cleaning up..."
  
task "build", "Build the project files", ->
  console.log "building..."
  
task "package", "Clean, build, and package the project", ->
  invoke "clean"
  invoke "build"
  console.log "packaging..."